config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :posts
  get "/" => "posts#index"
  
  post "/follows" => "follows#create"
  delete "/unfollows" => "follows#destroy"
  post "/log_in" => "session#create"
  delete "/log_out" => "session#destroy"
  

end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, foreign_key: :follower_id, class_name: User
  belongs_to :followee, foreign_key: :followee_id, class_name: User

  validates :follower_id, :uniqueness => {:scope => :followee_id}
  validate :check_same_user

  def check_same_user
      errors.add(:follower, "can't follow yourself") if self.follower_id == self.followee_id
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png" 
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


  def self.follow(users, id)
    users.each do |user|
     return true  if user.id == id
    end 
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :follows, foreign_key: :followee_id
  has_many :followings, foreign_key: :follower_id, class_name: "::Follow"
  has_many :followers, through: :follows, class_name: User
  has_many :followees, through: :followings, class_name: User

  attr_accessor :password
  validates_presence_of :fname, :lname, :uname, :password, :password_confirmation, :email, :location, :avatar
  validates_confirmation_of :password
  validates :email,:uname, uniqueness: true
  before_save :downcase_fields
  before_save :encrypt_password
  
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png" 
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
 
  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(uname, password)
    user = User.where(uname: uname).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def downcase_fields
    self.fname.downcase!
    self.lname.downcase!
    self.uname.downcase!
    self.email.downcase!
    self.location.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:id]) if session[:id]
  end
  helper_method :current_user
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    @follow=Follow.create(follow_params)
    redirect_to :back
  end

  def destroy
    @delete_follow_id=Follow.where(follower_id: params[:follower_id], followee_id: params[:followee_id]).first.id 
    Follow.destroy(@delete_follow_id)
    redirect_to :back
  end

  private
  
  def follow_params
    params.require(:follow).permit(:followee_id, :follower_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post=Post.new
    @old_post=Post.where(user_id: current_user.id)
  end

  def index
    @post=Post.order("id").reverse_order.limit(10) 
    @follow=Follow.new
  end
  def create
   @post=Post.create(post_params) 
   redirect_to :back
  end

 private
  
  def post_params
    params.require(:post).permit(:subject, :body, :user_id, :avatar)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    @user = User.authenticate(params[:uname], params[:password])
    if @user
      session[:id] = @user.id
      session[:username] = @user.uname
      redirect_to "/"
    else
      flash[:alert] = "********Username / Password incorrect ********"
      redirect_to new_user_path
    end
  end

  def destroy
    session[:id] = nil
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user=User.new
    @user.save
  end

  def show
    @old_post=Post.where(user_id: current_user.id)
  end

  def edit
    @user=User.new
  end

  def create
    @user=User.create(user_params)
    @user.save
    flash[:welcome] = "---------Welcome to the site ! please sign in now---------" if @user.save
    if @user.errors.full_messages.any?  
      @user.errors.full_messages.each do |error_message| 
      flash[:fname]= "* first name "+ error_message.downcase.split.drop(1).join(' ') if error_message.include? "Fname"
      flash[:lname]= "* last name "+ error_message.downcase.split.drop(1).join(' ') if error_message.include? "Lname"
      flash[:uname]= "* username "+ error_message.downcase.split.drop(1).join(' ')  if error_message.include? "Uname"
      flash[:password]= "* password "+ error_message.downcase.split.drop(2).join(' ')  if error_message.include? "Password"
      flash[:password_confirmation]= "* password "+ error_message.downcase.split.drop(2).join(' ')  if error_message.include? "Password"
      flash[:email]= "* " + error_message.downcase if error_message.include? "Email"
      flash[:location]= "* " + error_message.downcase if error_message.include? "Location"
      flash[:avatar]= "* " + error_message.downcase if error_message.include? "Avatar"

      end   
    end
  redirect_to :back
  end

  def update
    @user=current_user
    if @user.update_attributes(user_params)
      flash[:update]="*************** Update Succeed ***************"
    else
    #if @user.errors.full_messages.any?  
      @user.errors.full_messages.each do |error_message| 
      flash[:fname]= "* first name "+ error_message.downcase.split.drop(1).join(' ') if error_message.include? "Fname"
      flash[:lname]= "* last name "+ error_message.downcase.split.drop(1).join(' ') if error_message.include? "Lname"
      flash[:uname]= "* username "+ error_message.downcase.split.drop(1).join(' ')  if error_message.include? "Uname"
      flash[:password]= "* password "+ error_message.downcase.split.drop(2).join(' ')  if error_message.include? "Password"
      flash[:password_confirmation]= "* password "+ error_message.downcase.split.drop(2).join(' ')  if error_message.include? "Password"
      flash[:email]= "* " + error_message.downcase if error_message.include? "Email"
      flash[:location]= "* " + error_message.downcase if error_message.include? "Location"
      end   
    end
    redirect_to :back
  end

  def destroy
    User.destroy(current_user.id)
    session[:id]=nil
    flash[:welcome]="Your Account has beeen Deleted"
    redirect_to new_user_path
  end
  private
  
  def user_params
    params.require(:user).permit(:fname, :lname, :uname, :email, :password, :password_confirmation, :location, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
" hi hi hi "

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>foodie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Quicksand:400,300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <script type="text/javascript" src="jquery.blockUI.js"></script> 
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
</head>
</head>
<body>
  <div id="wrapper"> 
	  <header id="header">
      <div id="left_head">
        <p id="logo">Foodie</p>
      </div>
      <div id="center_head">
        <% if session[:id]%>
          <%= form_tag log_out_path, :method => :delete, :id => "log_out" do %>
            <%= label_tag :field, "Welcome back \" #{current_user.uname}\"" ,:id =>"log_in_back" %> 
            <%= submit_tag "log out" , :id => "log_out_buttom"%>
            <%end%>
          <% else %>
            <h5><%= flash[:alert] if flash[:alert] %></h5> 
          <%= form_tag log_in_path, :id => "log_in"  do %>
            <%= label_tag :field, "Username" %>
            <%= text_field_tag :uname, nil, :placeholder => "username" %>
            <%= label_tag :field, "Password" %>
            <%= text_field_tag :password ,nil, :placeholder => "password"  %>
            <%= submit_tag "log in" %>
            <%= link_to "Sign Up", new_user_path, :id=>"sign_link" %>
          <% end %>
        <% end %>
      </div>
      <div id=right_head>
        <ul>
          <li><a href="https://www.facebook.com"><i class="fa fa-facebook-square fa-lg"></i></a></li>
          <li><a href="https://www.twitter.com"><i class="fa fa-twitter-square fa-lg"></i></a></li>
          <li><a href="https://www.instagram.com"><i class="fa fa-instagram fa-lg"></i></a></li>
          <li><a href="https://www.pinterest.com"><i class="fa fa-pinterest-p fa-lg"></i></a></li>
        </ul>
      </div>
    </header>   
        
    <div id="sidebar">
      <% if session[:id] %>    
        <div id=profile_picture">
          <%= image_tag current_user.avatar.url, :id=>"pic" %>
        </div>
      <% else %>
        <div id="profile_picture">
          <img id="pic"src=<%= asset_path "stock_profile.jpg"%>>	
        </div>
      <% end %>
      <div id="user_info">
        <div id="user_info_list">
            <% if session[:id] %>
              <ul>
                <li>Username : <%= current_user.uname %></li>
                <li> Name : <%= current_user.fname.capitalize %> <%= current_user.lname.capitalize[0] %>.</li>
                <li><i class="fa fa-map-marker"></i> Location : <%= current_user.location.upcase %></li>
              </ul>
            <% else %>    
              <ul>
                <li>Username :</li>
                <li>  Name :</li>
                <li><i class="fa fa-map-marker"></i> Location :</li>
              </ul>
            <%end%>
        </div>
      </div>
      <div id="following">
        <div id="following_images">
          <%if session[:id]%>
            <% @users=User.find(session[:id]).followees%>
            <% @users.each do |user| %>
              <%= link_to image_tag(user.avatar.url, :border => 0, :alt => ""), users_path, :class =>"following_images_padding" %>
            <% end %>
          <% else %>
            <img class="following_images_padding" src=<%= asset_path "stock_profile.jpg" %>>
            <img class="following_images_padding" src=<%= asset_path "stock_profile.jpg" %>>
            <img class="following_images_padding" src=<%= asset_path "stock_profile.jpg" %>>
            <img class="following_images_padding" src=<%= asset_path "stock_profile.jpg" %>>
            <img class="following_images_padding" src=<%= asset_path "stock_profile.jpg" %>>
            <img class="following_images_padding" src=<%= asset_path "stock_profile.jpg" %>>
            <img class="following_images_padding" src=<%= asset_path "stock_profile.jpg" %>>
            <img class="following_images_padding" src=<%= asset_path "stock_profile.jpg" %>>
            <img class="following_images_padding" src=<%= asset_path "stock_profile.jpg" %>>
          <% end%>
        </div>
      </div>
    </div>
    
    <div id="content">     
      <div id=nav_icon>
        <i id="icon" class="fa fa-chevron-circle-down fa-2x"></i>
      </div>
      <div id="navbar">
        <% if session[:id] %>
          <ul>
            <li><div class="menu"><%= link_to "Profile", user_path(current_user.id) %></div></li>
            <li><div class="menu"><%= link_to "Feed", posts_path %></div></li>
            <li><div class="menu"><%= link_to "Account Edit", edit_user_path(current_user.id) %></div></li>
            <li><div class="menu"><%= link_to "Post", new_post_path %></div></li>
          </ul>
        <% else %>
          <ul>
            <li><div class="menu"><%= link_to "Profile", new_user_path %></div></li>
            <li><div class="menu"><%= link_to "Feed", new_user_path %></div></li>
            <li><div class="menu"><%= link_to "Account Edit", new_user_path %></div></li>
            <li><div class="menu"><%= link_to "Post", new_user_path %></div></li>
          </ul>
        <% end %>
      </div>
      <%=yield%>
    </div>
    
    <footer>
	    <div id="footer_about">
		    <ul>
			    <li><a href="#">About</a></li> |
			    <li><a href="#">FAQ</a></li> |
			    <li><a href="#">Contact Us</a></li>
        </ul> 
        <ul>
          <li><a href="https://www.facebook.com"><i class="fa fa-facebook-square fa-lg"></i></a></li>
          <li><a href="https://www.twitter.com"><i class="fa fa-twitter-square fa-lg"></i></a></li>
          <li><a href="https://www.instagram.com"><i class="fa fa-instagram fa-lg"></i></a></li>  
          <li><a href="https://www.pinterest.com"><i class="fa fa-pinterest-p fa-lg"></i></a></li>      
        </ul>
      </div>
      <div id="social list">
      </div>
	    <div id="footer_p">
        <p> Copyright &copy; 2015 Victor Tsay & John Paul Tambini. All rights reserved </p>
	    </div>
    </footer>
  </div> 
  <script> 
    $(document).ready(function(){
      var turn=0
      $("#icon").click(function(){
        if (turn==0){
          $("#navbar").animate({height: '300px', opacity: '.9'}, "slow");
          $("#navbar").css("z-index", "3");
            turn=1
        }else{
          $("#navbar").animate({height: '0', opacity: '0'}, "fast");
           $("#navbar").css("z-index", "0");
            turn=0
        }
      });
    });    
  </script>
</body>
</html>

app/views/posts/index.html.erb
<div id="feed_wrapper">
  <% (0..2).each do |i| %>
    <% if i%2 == 0 %>
      <div class="recent_feeds">
        <div class="feed_image"><%= image_tag @post[i].avatar.url %></div>
        <div class="feed_body">
          <h4><%=@post[i].subject%></h4>
          <h5 class=feed_name><%= @post[i].user.uname %></h5>
          <h5 class=feed_time><%= @post[i].created_at.to_s.chomp("UTC") %></h5>
          <p><%= @post[i].body %></p>
        </div>
        <% if session[:id] %>
          <% users1=@post[i].user.followers %>
          <% if  Post.follow(users1,current_user.id)== true %>
            <%= form_tag unfollows_path, :method => :delete do %>
              <%= hidden_field_tag :followee_id, @post[i].user.id %>
              <%= hidden_field_tag :follower_id, current_user.id %>
              <%= submit_tag "following", :class => "feed_button" %>
            <% end %>
          <% else %>
              <%= form_for @follow do |f| %>
                <%= f.hidden_field :followee_id, :value => @post[i].user.id %>
                <%= f.hidden_field :follower_id, :value => current_user.id %>
                <%= f.submit "Follow" ,:class => "feed_button" %>
              <% end %>
          <% end %>
        <% end %>
      </div>
    <% else %>
      <div class="recent_feeds_2">
        <div class="feed_image"><%= image_tag @post[i].avatar.url %></div>
        <div class="feed_body">
          <h4><%= @post[i].subject %></h4>
          <h5 class=feed_name><%= @post[i].user.uname %></h5>
          <h5 class=feed_time><%= @post[i].created_at.to_s.chomp("UTC") %></h5>
          <p><%= @post[i].body %></p>
        </div>
        <% if session[:id] %>
          <% users1=@post[i].user.followers %>
            <% if  Post.follow(users1,current_user.id)== true %>
              <%= form_tag unfollows_path, :method => :delete do %>
                <%= hidden_field_tag :followee_id, @post[i].user.id %>
                <%= hidden_field_tag :follower_id, current_user.id %>
                <%= submit_tag "following", :class => "feed_button" %>
              <% end %>
            <% else %>
                <%= form_for @follow do |f| %>
                  <%= f.hidden_field :followee_id, :value => @post[i].user.id %>
                  <%= f.hidden_field :follower_id, :value => current_user.id %>
                  <%= f.submit "Follow" ,:class => "feed_button" %>
                <% end %>
            <% end %> 
        <% end %>
      </div>
    <% end %>
  <%end%>
</div>

app/views/posts/new.html.erb
<div id="post">
    <div>
        <h1 id="post_h1">Posts</h1>
    </div>
    <div id="old_posts">
      <% @old_post.reverse.each do |post| %>
        <div id="post_img">
          <%= image_tag post.avatar.url(:thumb)%>
        </div>       
        <div id="post_body">  
          <h5><%= post.subject%></h5>
          <h6><%= post.created_at.to_s.chomp("UTC") %></h6>
          <p><%= post.body%></p>   
        </div>
      <% end %>
    </div>
    <%= form_for @post, :url => posts_path, :html => { :multipart => true } do |f| %> 
      <%= f.hidden_field :user_id, :value =>current_user.id %>
      <%= f.text_field :subject, :placeholder => "topic", :id=>"post_form_field" %>
      <%= f.text_area :body, cols: 80, rows:15, :placeholder=>"please enter posts here", :id=>"post_text" %>
      <h5><%= f.label :upload_picture %></h5> 
      <%= f.file_field :avatar, :id=>"posts_upload" %>
      <%=f.submit "Submit", data: {disable_with: "Submitting..."}, :id=>"post_submit" %>
    <%end%>
</div>

app/views/users/edit.html.erb
<div id="edit">
  <div id="edit_left">
      <h3>Account Info / Edit </h3>
  </div>
  <div>
    <%= form_for @user, :url => user_path(current_user.id), :method => :put, :id => "edit_form", :html => { :multipart => true } do |f| %>
      <h4><%= flash[:update] if flash[:update] %></h4>
      <h3><%= f.label :first_name, :class=>"title" %></h3>   
      <%= f.text_field :fname, :value => current_user.fname, :class=>"edit_field" %>
      <h6><%= flash[:fname] if flash[:fname] %></h6>
      
      <h3><%= f.label :last_name, :class=>"title" %></h3>   
      <%= f.text_field :lname, :value => current_user.lname, :class=>"edit_field" %>
      <h6><%= flash[:lname] if flash[:lname] %></h6>
      
      <h3><%= f.label :username, :class=>"title" %></h3>   
      <%= f.text_field :uname, :value => current_user.uname,:class=>"edit_field" %>
      <h6><%= flash[:uname] if flash[:uname] %></h6>
      
      <h3><%= f.label "Password", :class=>"title" %></h3>   
      <%= f.text_field :password, :placeholder => "re-enter your password",:class=>"edit_field" %>
      <h6><%= flash[:password] if flash[:password]%></h6>
         
      <h3><%= f.label "Password conformation", :class=>"title" %></h3>   
      <%= f.text_field :password_confirmation, :placeholder => "re-enter password confirmation",:class=>"edit_field"%>
      <h6><%= flash[:password_confirmation] if flash[:password_confirmation] %></h6>
      
      <h3><%= f.label :email, :class=>"title" %></h3> 
      <%= f.text_field :email, :value => current_user.email,:class=>"edit_field" %>
      <h6><%= flash[:email] if flash[:email]%></h6>
      
      <h3><%= f.label :city_and_state, :class=>"title" %></h3> 
      <%= f.text_field :location, :value => current_user.location,:class=>"edit_field" %> 
      <h6><%= flash[:location] if flash[:location]%></h6>
      
      <h3><%= f.label :upload_pictures, :class=>"title" %></h3> 
      <%= f.file_field :avatar %><br>
      <div id="change_buttom"><%=f.submit "Update Info", data: {disable_with: "updating..."}, :class=>"bottom" %></div>
    <% end %>
    <div>
      <%= form_for @user, :url => user_path(current_user.id), :method => :delete  do |f|  %>
      <%= f.submit "Delete Account",:class=>"bottom"%>
    <% end %>
  </div>
  <div id="edit_right"> </div>
</div>
</div>

app/views/users/new.html.erb
<div id="sign_up">
   <h5> <%=flash[:welcome] if flash[:welcome] %></h5>
  <div id="sign_left">
    <h3> Create New Account </h3>
  </div>
  <%= form_for @user, :url => users_path, :html => { :multipart => true } do |f| %>   
    <h3><%= f.label :first_name, :class=>"title" %></h3>   
    <%= f.text_field :fname, :placeholder => "first name", :class=>"sign_field" %>
    <h6><%= flash[:fname] if flash[:fname] %></h6>

    <h3><%= f.label :last_name, :class=>"title" %></h3>   
    <%= f.text_field :lname, :placeholder => "last name", :class=>"sign_field" %>
    <h6><%= flash[:lname] if flash[:lname] %></h6>

    <h3><%= f.label :username, :class=>"title" %></h3>   
    <%= f.text_field :uname, :placeholder => "usernam",:class=>"sign_field" %>
    <h6><%= flash[:uname] if flash[:uname] %></h6>

    <h3><%= f.label "Password", :class=>"title" %></h3>   
    <%= f.text_field :password, :placeholder => "password",:class=>"sign_field" %>
    <h6><%= flash[:password] if flash[:password]%></h6>

    <h3><%= f.label "Password conformation", :class=>"title" %></h3>   
    <%= f.text_field :password_confirmation, :placeholder => "password confirmation",:class=>"sign_field"%>
    <h6><%= flash[:password_confirmation] if flash[:password_confirmation] %></h6>

    <h3><%= f.label :email, :class=>"title" %></h3> 
    <%= f.text_field :email, :placeholder => "email",:class=>"sign_field" %>
    <h6><%= flash[:email] if flash[:email]%></h6>

    <h3><%= f.label :city_and_state, :class=>"title" %></h3> 
    <%= f.text_field :location, :placeholder => "city and state",:class=>"sign_field" %> 
    <h6><%= flash[:location] if flash[:location]%></h6>

    <h3><%= f.label :upload_pictures, :class=>"title" %></h3> 
    <%= f.file_field :avatar %><br>
    <h6><%= flash[:avatar] if flash[:avatar]%></h6>

    <div id="change_buttom">
        <%= f.submit "Reset", :type => "reset", :class=>"bottom" %>
        <%=f.submit "Sign up", data: {disable_with: "Submitting..."}, :class=>"bottom" %>
    </div>
  <% end %>
      <%=flash[:alert] if flash[:alert]%> 
</div>

app/views/users/show.html.erb
<div id="post">
    
    <div>
        <h1 id="post_h1">Profile</h1>
    </div>
    <div id="profile_info">
        <ul>
            <li>Name:  <%= current_user.fname.capitalize%> <%= current_user.lname.capitalize%></li>
            <li>Username: <%= current_user.uname%></li>
            <li>Email:  <%= current_user.email%></li>
            <li>Location: <%= current_user.location%></li>
            <!--<li> #@follow_id %></li>-->
        </ul>
    </div>
    <div>
      <h1 id="post_h1">Posts</h1>
    </div>
    <div id="old_posts">
      <% @old_post.reverse.each do |post| %>
        <div id="post_img">
          <%= image_tag post.avatar.url(:thumb)%>
        </div>       
        <div id="post_body">  
          <h5><%= post.subject%></h5>
          <h6><%= post.created_at.to_s.chomp("UTC") %></h6>
          <p><%= post.body%></p>   
        </div>
      <% end %>
    </div>
</div>